### ISSUE TITLE
Fixing border area tax rates

### ISSUE THREAD

**Issue by dfsnow** [AleaWM/CookCounty-PropertyTaxes#1]
Hi @AleaWM. Dan here, I'm a maintainer of [PTAXSIM](https://github.com/ccao-data/ptaxsim). I was reading through your reporting in this repo and noticed the [issues you were having with municipalities that cross county lines](https://github.com/AleaWM/CookCounty-PropertyTaxes/blob/6a3e4f737e9453d74cdaaa71dd02a936da6bda63/Residential_Burden_Shift.Rmd#L301).

I opened an investigation issue at https://github.com/ccao-data/ptaxsim/issues/10. Can you expand on any issues you encountered with county-crossing municipalities? The tax rates *should* be calculated correctly since the extension used in PTAXSIM is effectively prorated to the Cook-only portion of the total extension.

**Comment by AleaWM** [comment]
Hi! Short answer and good news: there doesn't appear to be an issue with the data for the counties that crossed municipalities. Tax rates at the tax code level and municipality composite tax rates appeared to be correct and were not causing problems.

Longer answer: I was calculating the percent of EAV that was residential vs other property classes. We were also calculating tax burden (share of levy paid by each property class/taxable EAV in the property class) for each property classes with and without exemptions. Frankfort, Oak Brook, Deerfield, etc. had skewed percentages for some of the statistics so they were removed since little EAV was within Cook County.  For some county crossing municipalities,  the percentages and ratios calculated did not match people's mental picture of a couple municipalities. I was advised to drop all municipalities with less than 50% of their EAV in Cook County for this specific research task and the summary statistics that were being provided to non-research team stakeholders.

**Comment by dfsnow** [comment]
Makes sense! Thank you for the additional context. I'll close this and the linked issue.
